<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StoreTypesSeeder extends Seeder
{
    public function run(): void
    {
        // Notlar:
        // - upsert(uniqueBy: id) => var olanı UPDATE eder, yoksa INSERT eder.
        // - created_at NULL olanları NULL bırakıyoruz (dump ile birebir).
        // - updated_at değerlerini dump'taki gibi birebir koruyoruz.

        $rows = [
            [
                'id' => 1,
                'name' => 'Market',
                'type' => 'grocery',
                'image' => '1297',
                'description' => 'Günlük market alışverişi: taze gıda, temel ihtiyaçlar ve hızlı teslimat.',
                'total_stores' => 1,
                'additional_charge_enable_disable' => 1,
                'additional_charge_name' => 'Paketleme Ücreti',
                'additional_charge_amount' => 10.00,
                'additional_charge_type' => 'percentage',
                'additional_charge_commission' => 5.00,
                'status' => 1,
                'created_at' => null,
                'updated_at' => '2025-09-28 03:27:06',
            ],
            [
                'id' => 2,
                'name' => 'Fırın & Pastane',
                'type' => 'bakery',
                'image' => '1297',
                'description' => 'Günlük taze ekmek, pasta, börek ve fırın ürünleri.',
                'total_stores' => 1,
                'additional_charge_enable_disable' => 0,
                'additional_charge_name' => 'Paketleme Ücreti',
                'additional_charge_amount' => 10.00,
                'additional_charge_type' => 'percentage',
                'additional_charge_commission' => 5.00,
                'status' => 1,
                'created_at' => null,
                'updated_at' => '2025-09-23 04:37:58',
            ],
            [
                'id' => 3,
                'name' => 'Eczane',
                'type' => 'medicine',
                'image' => '1297',
                'description' => 'Reçeteli / reçetesiz ürünler ve sağlık ihtiyaçları için güvenilir alışveriş.',
                'total_stores' => 1,
                'additional_charge_enable_disable' => 1,
                'additional_charge_name' => 'Güvenli Teslim Ücreti',
                'additional_charge_amount' => 10.00,
                'additional_charge_type' => 'fixed',
                'additional_charge_commission' => 2.00,
                'status' => 1,
                'created_at' => null,
                'updated_at' => '2025-09-23 01:05:57',
            ],
            [
                'id' => 4,
                'name' => 'Kozmetik',
                'type' => 'makeup',
                'image' => '1297',
                'description' => 'Makyaj, cilt bakımı ve kişisel bakım ürünleri.',
                'total_stores' => 1,
                'additional_charge_enable_disable' => 1,
                'additional_charge_name' => 'Paketleme Ücreti',
                'additional_charge_amount' => 12.00,
                'additional_charge_type' => 'percentage',
                'additional_charge_commission' => 10.00,
                'status' => 1,
                'created_at' => null,
                'updated_at' => '2025-09-23 01:05:48',
            ],
            [
                'id' => 5,
                'name' => 'Çanta',
                'type' => 'bags',
                'image' => '1297',
                'description' => 'El çantası, sırt çantası, valiz ve aksesuarlar.',
                'total_stores' => 1,
                'additional_charge_enable_disable' => 1,
                'additional_charge_name' => 'Paketleme Ücreti',
                'additional_charge_amount' => 10.00,
                'additional_charge_type' => 'percentage',
                'additional_charge_commission' => 15.00,
                'status' => 1,
                'created_at' => null,
                'updated_at' => '2025-09-23 01:05:46',
            ],
            [
                'id' => 6,
                'name' => 'Giyim',
                'type' => 'clothing',
                'image' => '1297',
                'description' => 'Kadın, erkek, çocuk giyim ve sezon ürünleri.',
                'total_stores' => 1,
                'additional_charge_enable_disable' => 0,
                'additional_charge_name' => 'Paketleme Ücreti',
                'additional_charge_amount' => 10.00,
                'additional_charge_type' => 'percentage',
                'additional_charge_commission' => 12.00,
                'status' => 1,
                'created_at' => null,
                'updated_at' => '2025-09-23 01:05:57',
            ],
            [
                'id' => 7,
                'name' => 'Mobilya',
                'type' => 'furniture',
                'image' => '1297',
                'description' => 'Ev ve ofis mobilyaları, dekorasyon ve yaşam ürünleri.',
                'total_stores' => 1,
                'additional_charge_enable_disable' => 0,
                'additional_charge_name' => 'Paketleme Ücreti',
                'additional_charge_amount' => 10.00,
                'additional_charge_type' => 'percentage',
                'additional_charge_commission' => 10.00,
                'status' => 1,
                'created_at' => null,
                'updated_at' => '2025-09-23 01:05:49',
            ],
            [
                'id' => 8,
                'name' => 'Kitap',
                'type' => 'books',
                'image' => '1297',
                'description' => 'Roman, eğitim, çocuk kitapları ve diğer yayınlar.',
                'total_stores' => 1,
                'additional_charge_enable_disable' => 1,
                'additional_charge_name' => 'Paketleme Ücreti',
                'additional_charge_amount' => 5.00,
                'additional_charge_type' => 'fixed',
                'additional_charge_commission' => 5.00,
                'status' => 1,
                'created_at' => null,
                'updated_at' => '2025-09-23 01:05:48',
            ],
            [
                'id' => 9,
                'name' => 'Teknoloji',
                'type' => 'gadgets',
                'image' => '1297',
                'description' => 'Telefon, aksesuar, elektronik ürünler ve teknoloji ekipmanları.',
                'total_stores' => 1,
                'additional_charge_enable_disable' => 1,
                'additional_charge_name' => 'Paketleme Ücreti',
                'additional_charge_amount' => 10.00,
                'additional_charge_type' => 'percentage',
                'additional_charge_commission' => 10.00,
                'status' => 1,
                'created_at' => null,
                'updated_at' => '2025-09-23 01:05:46',
            ],
            [
                'id' => 10,
                'name' => 'Evcil Hayvan',
                'type' => 'animals-pet',
                'image' => '1297',
                'description' => 'Evcil hayvan maması, oyuncak, aksesuar ve bakım ürünleri.',
                'total_stores' => 1,
                'additional_charge_enable_disable' => 1,
                'additional_charge_name' => 'Özel Paketleme Ücreti',
                'additional_charge_amount' => 20.00,
                'additional_charge_type' => 'fixed',
                'additional_charge_commission' => 30.00,
                'status' => 1,
                'created_at' => null,
                'updated_at' => '2025-09-23 04:38:45',
            ],
            [
                'id' => 11,
                'name' => 'Balık & Deniz',
                'type' => 'fish',
                'image' => '1297',
                'description' => 'Taze balık, deniz ürünleri ve soğuk zincirle teslim edilebilen ürünler.',
                'total_stores' => 1,
                'additional_charge_enable_disable' => 0,
                'additional_charge_name' => 'Soğuk Zincir Ücreti',
                'additional_charge_amount' => 10.00,
                'additional_charge_type' => 'percentage',
                'additional_charge_commission' => 10.00,
                'status' => 1,
                'created_at' => null,
                'updated_at' => '2025-10-05 22:28:19',
            ],
        ];

        DB::transaction(function () use ($rows) {
            DB::table('store_types')->upsert(
                $rows,
                ['id'],
                [
                    'name',
                    'type',
                    'image',
                    'description',
                    'total_stores',
                    'additional_charge_enable_disable',
                    'additional_charge_name',
                    'additional_charge_amount',
                    'additional_charge_type',
                    'additional_charge_commission',
                    'status',
                    'created_at',
                    'updated_at',
                ]
            );
        });
    }
}
