INSERT INTO translations (translatable_type, translatable_id, language, `key`, `value`)
VALUES
('App\\Models\\Blog', 1, 'en', 'title', 'Boost Your Immunity: Essential Vitamins and Supplements You Need'),
('App\\Models\\Blog', 1, 'en', 'description', 'A strong immune system is crucial for fighting infections and staying healthy. Vitamins such as C, D, and E, along with minerals like zinc and iron, play key roles in supporting immunity. Vitamin C, found in citrus fruits, helps the body produce white blood cells that defend against infections. Vitamin D, obtained from sunlight and fortified foods, strengthens immune response and is also essential for bone health. Zinc supports immune cell function and wound healing, making it especially important during cold and flu season. Alongside supplements, a balanced diet rich in vegetables, fruits, nuts, and lean proteins is essential. Adequate hydration and quality sleep also contribute to overall immune health. Managing stress through practices like meditation or yoga can further improve immune function. By focusing on these nutrients and healthy habits, you can build a stronger defense against illness.'),
('App\\Models\\Blog', 1, 'en', 'meta_title', 'Boost Your Immunity: Essential Vitamins and Supplements You Need'),
('App\\Models\\Blog', 1, 'en', 'meta_description', 'A strong immune system is crucial for fighting infections and staying healthy.'),
('App\\Models\\Blog', 1, 'en', 'meta_keywords', 'Health, Wellness'),

('App\\Models\\Blog', 2, 'en', 'title', 'Baking 101: Tips for Perfect Pastries and Baked Goods'),
('App\\Models\\Blog', 2, 'en', 'description', 'Baking is both an art and a science—it requires precision and the right techniques. One of the most important factors is measuring ingredients accurately; even small deviations can affect the outcome. Having ingredients like eggs and butter at room temperature helps you achieve a smoother batter or dough. Preheating the oven is critical; placing batter into a cold oven often leads to uneven baking. Knowing your oven also matters—many ovens have hot spots, so rotating trays mid-bake can help achieve even results. Mixing methods such as folding, whisking, and beating influence the final texture. Beginners should start with simple recipes and build confidence before attempting advanced techniques. Finally, allow cakes and pastries to cool before frosting to prevent melting and a messy finish. With practice and patience, anyone can become a better baker.'),
('App\\Models\\Blog', 2, 'en', 'meta_title', 'Perfect Pastries and Baking Tips'),
('App\\Models\\Blog', 2, 'en', 'meta_description', 'Practical tips and techniques to improve your baking results.'),
('App\\Models\\Blog', 2, 'en', 'meta_keywords', 'Baking, Pastry'),

('App\\Models\\Blog', 3, 'en', 'title', 'Smart Grocery Shopping: Save Money and Reduce Waste'),
('App\\Models\\Blog', 3, 'en', 'description', 'Grocery shopping can get expensive when it is not planned well. The key to saving money is creating a well-prepared shopping list based on a weekly meal plan. Buying in bulk and choosing seasonal produce can reduce costs while giving you fresher ingredients. Another smart tip is to stick to your list and avoid shopping while hungry, which helps prevent impulse purchases. Understanding date labels and using proper storage techniques also reduces food waste. Many people throw away perfectly good food because they confuse “best before” dates with “use by” dates. Tracking discount stores, loyalty programs, and digital coupons can further increase savings. By applying these strategies, you can lower your spending and make more sustainable choices.'),
('App\\Models\\Blog', 3, 'en', 'meta_title', 'Smart Grocery Shopping'),
('App\\Models\\Blog', 3, 'en', 'meta_description', 'Grocery shopping becomes costly without planning—learn how to save and waste less.'),
('App\\Models\\Blog', 3, 'en', 'meta_keywords', 'Grocery, Shopping, Savings, Smart'),

('App\\Models\\Blog', 4, 'en', 'title', 'Must-Have Makeup Products for Every Skin Type'),
('App\\Models\\Blog', 4, 'en', 'description', 'Choosing the right makeup products supports healthy skin while enhancing your natural beauty. Oily skin benefits from matte foundations and oil-free primers that control shine and help prevent clogged pores. Dry skin does best with hydrating foundations and creamy concealers that provide moisture and coverage. For combination skin, balance is key—lightweight foundations that control oil in the T-zone while keeping other areas comfortable work well. Sensitive skin often needs fragrance-free, hypoallergenic formulas to reduce irritation. A good setting spray helps makeup last all day regardless of skin type. Multi-purpose products like BB creams or tinted moisturizers can simplify your routine while offering skincare benefits. Keeping makeup brushes clean is also important to prevent bacteria buildup and breakouts. Finding products that match your skin’s needs can make a noticeable difference in your everyday makeup routine.'),
('App\\Models\\Blog', 4, 'en', 'meta_title', 'Must-Have Makeup for Every Skin Type'),
('App\\Models\\Blog', 4, 'en', 'meta_description', 'The right makeup choices can protect skin health and enhance natural beauty.'),
('App\\Models\\Blog', 4, 'en', 'meta_keywords', 'Beauty, Makeup'),

('App\\Models\\Blog', 5, 'en', 'title', 'Wardrobe Essentials: Must-Have Fashion Staples for Every Season'),
('App\\Models\\Blog', 5, 'en', 'description', 'A well-organized wardrobe is built around timeless pieces that can be styled for many occasions. A classic white shirt is a must-have; pair it with jeans for a casual look or tailored trousers for a more formal style. Well-fitting denim offers year-round comfort and versatility. A little black dress is ideal for evening events, while a well-cut blazer instantly elevates almost any outfit. Comfortable sneakers and elegant heels provide options for both casual and dressy combinations. Accessories like a statement bag and a quality belt can upgrade your look in seconds. Investing in durable basics instead of fast fashion often brings better longevity and sustainability. With these wardrobe essentials, you will always have stylish choices no matter the season.'),
('App\\Models\\Blog', 5, 'en', 'meta_title', 'Wardrobe Essentials'),
('App\\Models\\Blog', 5, 'en', 'meta_description', 'How to build a timeless wardrobe with versatile staples for every season.'),
('App\\Models\\Blog', 5, 'en', 'meta_keywords', 'Fashion'),

('App\\Models\\Blog', 6, 'en', 'title', 'Small Space, Big Impact: Smart Furniture Choices for Compact Homes'),
('App\\Models\\Blog', 6, 'en', 'description', 'Living in a small space does not mean you have to sacrifice style or functionality. Multi-purpose furniture such as sofa beds and foldable dining tables maximizes space while maintaining comfort. Wall-mounted shelves and vertical storage solutions reduce clutter and save floor area. Mirrors reflect natural light and can make a room feel larger. Light-colored walls and furniture also enhance the sense of openness. Compact pieces with hidden storage—like ottomans—help keep things organized. Minimal decor prevents spaces from feeling crowded. Techniques such as under-bed storage and hanging organizers help you use every inch efficiently. With smart furniture choices, even the smallest home can be stylish and practical.'),
('App\\Models\\Blog', 6, 'en', 'meta_title', 'Smart Furniture for Small Spaces'),
('App\\Models\\Blog', 6, 'en', 'meta_description', 'Practical furniture ideas to make compact homes feel larger and more functional.'),
('App\\Models\\Blog', 6, 'en', 'meta_keywords', 'Home, Decor, Furniture'),

('App\\Models\\Blog', 7, 'en', 'title', 'Essential Pet Care Tips: Keep Your Pets Healthy and Happy'),
('App\\Models\\Blog', 7, 'en', 'description', '<p>Owning a pet is a big responsibility, and proper care is essential for their well-being. A balanced diet suited to your pet’s breed and size helps ensure they get the nutrients they need. Regular veterinary checkups help detect health issues early and keep vaccinations up to date. Exercise and playtime are crucial for preventing obesity and behavior problems. Grooming routines such as brushing, nail trimming, and ear cleaning keep pets comfortable and reduce the risk of infections. Providing a cozy bed and safe toys creates a comfortable living space and helps pets feel secure and engaged. Socializing with other animals and people improves behavior and reduces anxiety. Training with positive reinforcement strengthens the bond between pet and owner. By following these essential care tips, you can support your furry friends in living a happy and healthy life.</p>'),
('App\\Models\\Blog', 7, 'en', 'meta_title', 'Essential Pet Care Tips'),
('App\\Models\\Blog', 7, 'en', 'meta_description', 'Basic pet care guidance to keep your pets healthy, safe, and happy.'),
('App\\Models\\Blog', 7, 'en', 'meta_keywords', 'Pets, Care, Health')
ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
