-- Table structure for table `email_templates`
--

CREATE TABLE `email_templates` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `type` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `subject` varchar(255) DEFAULT NULL,
  `body` text DEFAULT NULL,
  `status` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1=active, 0=inactive',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `email_templates`
--

INSERT INTO `email_templates` (`id`, `type`, `name`, `subject`, `body`, `status`, `created_at`, `updated_at`) VALUES
(1, 'register', 'Kullanıcı Kaydı ffff', 'Hoş Geldiniz', '<h2> Hoş geldiniz @name </h2>\n<p> @site_name\`e katıldığınız için teşekkürler </p>\n<ul>\n  <li>E-posta: @email</li>\n  <li>Telefon: @phone</li>\n</ul>', 1, '2025-03-10 01:43:11', '2025-07-23 22:17:01'),
(2, 'password-reset', 'Şifre Sıfırlama', 'Laravel için Şifrenizi Sıfırlayın', '<h2>Merhaba @name,</h2><p>Şifrenizi sıfırlamak için bir talep aldık. Bu kodu kullanın:</p><h2>@reset_code</h2><p><i>Bu siz değilseniz lütfen bu e-postayı görmezden gelin.</i></p>', 1, '2025-03-10 01:43:11', '2025-07-23 22:18:19'),
(3, 'store-creation', 'Yeni Mağaza Oluşturuldu', 'Yeni Bir Mağaza Oluşturuldu', '<h1>Merhaba, @owner_name,</h1>\n                           <p><strong>@store_name</strong> mağazanız başarıyla oluşturuldu!</p>', 1, '2025-03-10 01:43:11', '2025-09-23 02:51:18'),
(4, 'subscription-expired', 'Abonelik Süresi Doldu Bildirimi', 'Aboneliğinizin Süresi Doldu!', '<h1>Merhaba, @owner_name,</h1>\n                           <p><strong>@store_name</strong> mağazası için aboneliğiniz @expiry_date tarihinde sona erdi.</p>\n                           <p>Hizmetlerimizi kullanmaya devam etmek için lütfen aboneliğinizi yenileyin.</p>', 1, '2025-03-10 01:43:11', '2025-03-25 00:00:44'),
(5, 'subscription-renewed', 'Abonelik Yenileme Onayı', 'Aboneliğiniz Başarıyla Yenilendi!', '<h1>Merhaba, @owner_name,</h1>\n                           <p><strong>@store_name</strong> mağazası için aboneliğiniz başarıyla yenilendi.</p>\n                           <p>Yeni Bitiş Tarihi: @new_expiry_date</p>\n                           <p>Bizimle kaldığınız için teşekkürler!</p>', 1, '2025-03-10 01:43:11', '2025-03-10 01:43:11'),
(6, 'order-created', 'Yeni Sipariş Oluşturuldu', 'Yeni Bir Siparişiniz Var!', '<h1>Merhaba @customer_name,</h1>\n                           <p>Siparişiniz (Sipariş No: @order_id) başarıyla oluşturuldu.</p>\n                           <p>Sipariş Tutarı: @order_amount</p>\n                           <p>Sipariş durumunuz değiştiğinde sizi bilgilendireceğiz.</p>', 1, '2025-03-10 01:43:11', '2025-03-10 01:43:11'),
(7, 'order-created-store', 'Mağazanız İçin Yeni Sipariş Oluşturuldu', 'Mağazanıza Yeni Bir Sipariş Geldi!', '<h1>Merhaba @store_owner_name,</h1>\n                           <p><strong>@store_name</strong> mağazanız yeni bir sipariş aldı (Sipariş No: @order_id).</p>\n                           <p>Sipariş Tutarı: @order_amount</p>\n                           <p>Lütfen siparişi en kısa sürede işleme alın.</p>', 1, '2025-03-10 01:43:11', '2025-03-10 01:43:11'),
(8, 'order-created-admin', 'Yeni Sipariş Oluşturuldu', 'Platformda Yeni Sipariş Verildi!', '<h1>Merhaba Admin,</h1>\n                           <p>Platformda yeni bir sipariş (Sipariş No: @order_id) oluşturuldu.</p>\n                           <p>Sipariş Tutarı: @order_amount</p>\n                           <p>Lütfen sipariş detaylarını inceleyin ve gerekli işlemleri yapın.</p>', 1, '2025-03-10 01:43:11', '2025-03-10 01:43:11'),
(9, 'order-status-pending', 'Sipariş Beklemede Bildirimi', 'Sipariş Durumunuz: Beklemede', '<h1>Merhaba @customer_name,</h1>\n                           <p>Siparişiniz (Sipariş No: @order_id) şu anda <strong>beklemede</strong>.</p>\n                           <p>Sipariş durumu değiştiğinde sizi bilgilendireceğiz.</p>', 1, '2025-03-10 01:43:11', '2025-03-10 01:43:11'),
(10, 'order-status-confirmed', 'Sipariş Onaylandı Bildirimi', 'Sipariş Durumunuz: Onaylandı', '<h1>Merhaba @customer_name,</h1>\n                           <p>Siparişiniz (Sipariş No: @order_id) <strong>onaylandı</strong>!</p>\n                           <p>İşleme alındığında sizi bilgilendireceğiz.</p>', 1, '2025-03-10 01:43:11', '2025-03-10 01:43:11'),
(11, 'order-status-processing', 'Sipariş Hazırlanıyor Bildirimi', 'Sipariş Durumunuz: Hazırlanıyor', '<h1>Merhaba @customer_name,</h1>\n                           <p>Siparişiniz (Sipariş No: @order_id) şu anda <strong>hazırlanıyor</strong>.</p>\n                           <p>Kargoya verildiğinde sizi bilgilendireceğiz.</p>', 1, '2025-03-10 01:43:11', '2025-03-10 01:43:11'),
(12, 'order-status-shipped', 'Sipariş Kargoya Verildi Bildirimi', 'Sipariş Durumunuz: Kargoya Verildi', '<h1>Merhaba @customer_name,</h1>\n                           <p>Siparişiniz (Sipariş No: @order_id) <strong>kargoya verildi</strong>!</p>\n                           <p>Size doğru yola çıktı ve yakında teslim edilecek.</p>', 1, '2025-03-10 01:43:11', '2025-03-10 01:43:11'),
(13, 'order-status-delivered', 'Sipariş Teslim Edildi Bildirimi', 'Siparişiniz Teslim Edildi!', '<h1>Merhaba @customer_name,</h1>\n                           <p>Siparişiniz (Sipariş No: @order_id) <strong>teslim edildi</strong>!</p>\n                           <p>Keyifli alışverişler dileriz!</p>', 1, '2025-03-10 01:43:11', '2025-03-10 01:43:11'),
(14, 'order-status-cancelled', 'Sipariş İptal Edildi Bildirimi', 'Siparişiniz İptal Edildi', '<h1>Merhaba @customer_name,</h1>\n                           <p>Siparişiniz (Sipariş No: @order_id) <strong>iptal edildi</strong>.</p>\n                           <p>Herhangi bir sorunuz varsa lütfen destek ekibimizle iletişime geçin.</p>', 1, '2025-03-10 01:43:11', '2025-03-10 01:43:11'),
(15, 'refund-customer', 'İade İşlemi Tamamlandı', 'İadeniz İşleme Alındı', '<h1>Merhaba @customer_name,</h1>\n                           <p>@order_id numaralı siparişiniz için iade işleminiz başarıyla tamamlandı.</p>\n                           <p>İade Tutarı: @refund_amount</p>\n                           <p>Tutar kısa süre içinde hesabınıza yansıtılacaktır.</p>', 1, '2025-03-10 01:43:11', '2025-03-10 01:43:11'),
(16, 'refund-store', 'Mağazanız İçin İade İşlemi Tamamlandı', 'Mağazanızdaki Bir Sipariş İçin İade İşlemi Yapıldı', '<h1>Merhaba @store_owner_name,</h1>\n                           <p>Mağazanızdaki bir sipariş için iade işlemi yapıldı (Sipariş No: @order_id).</p>\n                           <p>İade Tutarı: @refund_amount</p>\n                           <p>Lütfen hesabınızın buna göre güncellendiğinden emin olun.</p>', 1, '2025-03-10 01:43:11', '2025-03-10 01:43:11'),
(17, 'wallet-balance-added-customer', 'Müşteri Cüzdan Bakiyesi Eklendi', 'Cüzdan Bakiyeniz Güncellendi', '<h1>Merhaba @customer_name,</h1>\n                           <p>Cüzdan bakiyeniz başarıyla güncellendi.</p>\n                           <p>Yeni Bakiye: @balance</p>\n                           <p>Hizmetimizi kullandığınız için teşekkürler!</p>', 1, '2025-03-10 01:43:11', '2025-03-10 01:43:11'),
(18, 'wallet-balance-added-store', 'Mağaza Cüzdan Bakiyesi Eklendi', 'Mağaza Cüzdan Bakiyeniz Güncellendi', '<h1>Merhaba @store_owner_name,</h1>\n                           <p>Mağazanızın cüzdan bakiyesi başarıyla güncellendi.</p>\n                           <p>Mağaza: @store_name</p>\n                           <p>Yeni Bakiye: @balance</p>\n                           <p>Platformumuzun bir parçası olduğunuz için teşekkürler!</p>', 1, '2025-03-10 01:43:11', '2025-03-10 01:43:11'),
(19, 'store-withdrawal-request', 'Mağaza Para Çekme Talebi', 'Para Çekme Talebi Oluşturuldu', '<h1>Merhaba Admin,</h1>\n                           <p>@store_owner_name tarafından <strong>@store_name</strong> mağazası için bir para çekme talebi oluşturuldu.</p>\n                           <p>Talep Edilen Tutar: @amount</p>\n                           <p>Lütfen inceleyin ve gerekli işlemleri yapın.</p>', 1, '2025-03-10 01:43:11', '2025-03-10 01:43:11'),
(20, 'store-withdrawal-approved', 'Mağaza Para Çekme Onayı', 'Para Çekme Talebiniz Onaylandı', '<h1>Merhaba @store_owner_name,</h1>\n                           <p><strong>@store_name</strong> mağazanız için para çekme talebiniz onaylandı.</p>\n                           <p>Tutar: @amount</p>\n                           <p>Tutar kısa süre içinde hesabınıza aktarılacaktır.</p>', 1, '2025-03-10 01:43:11', '2025-03-10 01:43:11'),
(21, 'store-withdrawal-declined', 'Mağaza Para Çekme Reddedildi', 'Para Çekme Talebiniz Reddedildi', '<h1>Merhaba @store_owner_name,</h1>\n                           <p><strong>@store_name</strong> mağazanız için para çekme talebiniz reddedildi.</p>\n                           <p>Tutar: @amount</p>\n                           <p>Herhangi bir sorunuz varsa lütfen destek ekibiyle iletişime geçin.</p>', 1, '2025-03-10 01:43:11', '2025-03-10 01:43:11'),
(22, 'deliveryman-withdrawal-request', 'Kurye Para Çekme Talebi', 'Para Çekme Talebiniz Alındı', '<h1>Merhaba @deliveryman_name,</h1>\n                       <p>@amount tutarındaki para çekme talebiniz başarıyla oluşturuldu.</p>\n                       <p>Talebiniz admin tarafından inceleniyor. İşleminiz tamamlandığında bir onay e-postası alacaksınız.</p>\n                       <p>Emekleriniz için teşekkürler!</p>', 1, '2025-03-10 01:43:11', '2025-03-10 01:43:11'),
(23, 'deliveryman-earning', 'Kurye Kazanç Bildirimi', 'Yeni Kazançlarınız Var!', '<h1>Merhaba, @deliveryman_name,</h1>\n                            <p>Yeni bir kazanç aldınız:</p>\n                            <p><strong>Sipariş No:</strong> @order_id</p>\n                            <p><strong>Sipariş Tutarı:</strong> @order_amount</p>\n                            <p><strong>Kazanç:</strong> @earnings_amount</p>\n                            <p>Emekleriniz için teşekkürler!</p>', 1, '2025-03-10 01:43:11', '2025-03-10 01:43:11'),
(24, 'seller-register-for-admin', 'Kullanıcı Kaydı', 'Merhaba Admin, Yeni Bir Satıcı Katıldı!', '<ul>\n<li><strong>Ad Soyad:</strong> @name</li>\n<li><strong>E-posta:</strong> @email</li>\n<li><strong>Telefon:</strong> @phone</li>\n</ul>', 1, '2025-03-10 01:43:11', '2025-09-23 02:49:07');

-- --------------------------------------------------------

